package com.Model;
// Generated 2 oct. 2016 08:28:38 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer idClient;
     private String nomClient;
     private Long solde;
     private Set versements = new HashSet(0);
     private Set retraits = new HashSet(0);

    public Client() {
    }

    public Client(String nomClient, Long solde, Set versements, Set retraits) {
       this.nomClient = nomClient;
       this.solde = solde;
       this.versements = versements;
       this.retraits = retraits;
    }
   
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }
    public String getNomClient() {
        return this.nomClient;
    }
    
    public void setNomClient(String nomClient) {
        this.nomClient = nomClient;
    }
    public Long getSolde() {
        return this.solde;
    }
    
    public void setSolde(Long solde) {
        this.solde = solde;
    }
    public Set getVersements() {
        return this.versements;
    }
    
    public void setVersements(Set versements) {
        this.versements = versements;
    }
    public Set getRetraits() {
        return this.retraits;
    }
    
    public void setRetraits(Set retraits) {
        this.retraits = retraits;
    }




}


