package com.Model;
// Generated 2 oct. 2016 08:28:38 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Retrait generated by hbm2java
 */
public class Retrait  implements java.io.Serializable {


     private Long idRetrait;
     private Client client;
     private Long montant;
     private Date date;
     private int mois;
     private int annee;

    public Retrait() {
    }

	
    public Retrait(Client client, int mois, int annee) {
        this.client = client;
        this.mois = mois;
        this.annee = annee;
    }
    public Retrait(Client client, Long montant, Date date, int mois, int annee) {
       this.client = client;
       this.montant = montant;
       this.date = date;
       this.mois = mois;
       this.annee = annee;
    }
   
    public Long getIdRetrait() {
        return this.idRetrait;
    }
    
    public void setIdRetrait(Long idRetrait) {
        this.idRetrait = idRetrait;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Long getMontant() {
        return this.montant;
    }
    
    public void setMontant(Long montant) {
        this.montant = montant;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public int getMois() {
        return this.mois;
    }
    
    public void setMois(int mois) {
        this.mois = mois;
    }
    public int getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(int annee) {
        this.annee = annee;
    }




}


