package com.Model;
// Generated 2 oct. 2016 08:28:38 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Versement generated by hbm2java
 */
public class Versement  implements java.io.Serializable {


     private Long idVersement;
     private Client client;
     private Long montant;
     private Date date;
     private int mois;
     private int annee;

    public Versement() {
    }

	
    public Versement(Client client, int mois, int annee) {
        this.client = client;
        this.mois = mois;
        this.annee = annee;
    }
    public Versement(Client client, Long montant, Date date, int mois, int annee) {
       this.client = client;
       this.montant = montant;
       this.date = date;
       this.mois = mois;
       this.annee = annee;
    }
   
    public Long getIdVersement() {
        return this.idVersement;
    }
    
    public void setIdVersement(Long idVersement) {
        this.idVersement = idVersement;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Long getMontant() {
        return this.montant;
    }
    
    public void setMontant(Long montant) {
        this.montant = montant;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public int getMois() {
        return this.mois;
    }
    
    public void setMois(int mois) {
        this.mois = mois;
    }
    public int getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(int annee) {
        this.annee = annee;
    }

    public void setDate(String format) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


